spring:
  config:
    import: optional:classpath:.env
  application:
    name: InitiativeNouvelleAquitaine
  datasource:
    url: jdbc:postgresql://localhost:5432/Initiative
    username: postgres
    password: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
